Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
ano_atual: inteiro
ano_nasc: inteiro
idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o ano em que estamos? ")
leia (ano_atual)
escreva ("Digite o ano em que voce nasceu? ")
leia (ano_nasc)

idade <- ano_atual - ano_nasc

escreval ("Voce tem", idade," anos!")

Fimalgoritmo